/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutRagChatRouteImport } from './routes/_layout/rag-chat'
import { Route as LayoutModelConfigRouteImport } from './routes/_layout/model-config'
import { Route as LayoutCollectionRouteImport } from './routes/_layout/collection'
import { Route as LayoutAppSettingRouteImport } from './routes/_layout/app-setting'
import { Route as LayoutAccountRouteImport } from './routes/_layout/account'
import { Route as LayoutWikiTiptapEditorRouteImport } from './routes/_layout/wiki/tiptap-editor'
import { Route as LayoutWikiFoldersRouteImport } from './routes/_layout/wiki/folders'
import { Route as LayoutWikiDocumentsRouteImport } from './routes/_layout/wiki/documents'
import { Route as LayoutSystemUserRouteImport } from './routes/_layout/system/user'
import { Route as LayoutSystemRoleRouteImport } from './routes/_layout/system/role'
import { Route as LayoutSystemQueueRouteImport } from './routes/_layout/system/queue'
import { Route as LayoutSystemDepartmentRouteImport } from './routes/_layout/system/department'
import { Route as LayoutSystemAgentRouteImport } from './routes/_layout/system/agent'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRagChatRoute = LayoutRagChatRouteImport.update({
  id: '/rag-chat',
  path: '/rag-chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelConfigRoute = LayoutModelConfigRouteImport.update({
  id: '/model-config',
  path: '/model-config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCollectionRoute = LayoutCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppSettingRoute = LayoutAppSettingRouteImport.update({
  id: '/app-setting',
  path: '/app-setting',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountRoute = LayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWikiTiptapEditorRoute = LayoutWikiTiptapEditorRouteImport.update({
  id: '/wiki/tiptap-editor',
  path: '/wiki/tiptap-editor',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWikiFoldersRoute = LayoutWikiFoldersRouteImport.update({
  id: '/wiki/folders',
  path: '/wiki/folders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWikiDocumentsRoute = LayoutWikiDocumentsRouteImport.update({
  id: '/wiki/documents',
  path: '/wiki/documents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemUserRoute = LayoutSystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemRoleRoute = LayoutSystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemQueueRoute = LayoutSystemQueueRouteImport.update({
  id: '/system/queue',
  path: '/system/queue',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemDepartmentRoute = LayoutSystemDepartmentRouteImport.update({
  id: '/system/department',
  path: '/system/department',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemAgentRoute = LayoutSystemAgentRouteImport.update({
  id: '/system/agent',
  path: '/system/agent',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof LayoutAccountRoute
  '/app-setting': typeof LayoutAppSettingRoute
  '/collection': typeof LayoutCollectionRoute
  '/model-config': typeof LayoutModelConfigRoute
  '/rag-chat': typeof LayoutRagChatRoute
  '/system/agent': typeof LayoutSystemAgentRoute
  '/system/department': typeof LayoutSystemDepartmentRoute
  '/system/queue': typeof LayoutSystemQueueRoute
  '/system/role': typeof LayoutSystemRoleRoute
  '/system/user': typeof LayoutSystemUserRoute
  '/wiki/documents': typeof LayoutWikiDocumentsRoute
  '/wiki/folders': typeof LayoutWikiFoldersRoute
  '/wiki/tiptap-editor': typeof LayoutWikiTiptapEditorRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof LayoutAccountRoute
  '/app-setting': typeof LayoutAppSettingRoute
  '/collection': typeof LayoutCollectionRoute
  '/model-config': typeof LayoutModelConfigRoute
  '/rag-chat': typeof LayoutRagChatRoute
  '/': typeof LayoutIndexRoute
  '/system/agent': typeof LayoutSystemAgentRoute
  '/system/department': typeof LayoutSystemDepartmentRoute
  '/system/queue': typeof LayoutSystemQueueRoute
  '/system/role': typeof LayoutSystemRoleRoute
  '/system/user': typeof LayoutSystemUserRoute
  '/wiki/documents': typeof LayoutWikiDocumentsRoute
  '/wiki/folders': typeof LayoutWikiFoldersRoute
  '/wiki/tiptap-editor': typeof LayoutWikiTiptapEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/account': typeof LayoutAccountRoute
  '/_layout/app-setting': typeof LayoutAppSettingRoute
  '/_layout/collection': typeof LayoutCollectionRoute
  '/_layout/model-config': typeof LayoutModelConfigRoute
  '/_layout/rag-chat': typeof LayoutRagChatRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/system/agent': typeof LayoutSystemAgentRoute
  '/_layout/system/department': typeof LayoutSystemDepartmentRoute
  '/_layout/system/queue': typeof LayoutSystemQueueRoute
  '/_layout/system/role': typeof LayoutSystemRoleRoute
  '/_layout/system/user': typeof LayoutSystemUserRoute
  '/_layout/wiki/documents': typeof LayoutWikiDocumentsRoute
  '/_layout/wiki/folders': typeof LayoutWikiFoldersRoute
  '/_layout/wiki/tiptap-editor': typeof LayoutWikiTiptapEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/app-setting'
    | '/collection'
    | '/model-config'
    | '/rag-chat'
    | '/system/agent'
    | '/system/department'
    | '/system/queue'
    | '/system/role'
    | '/system/user'
    | '/wiki/documents'
    | '/wiki/folders'
    | '/wiki/tiptap-editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/app-setting'
    | '/collection'
    | '/model-config'
    | '/rag-chat'
    | '/'
    | '/system/agent'
    | '/system/department'
    | '/system/queue'
    | '/system/role'
    | '/system/user'
    | '/wiki/documents'
    | '/wiki/folders'
    | '/wiki/tiptap-editor'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/account'
    | '/_layout/app-setting'
    | '/_layout/collection'
    | '/_layout/model-config'
    | '/_layout/rag-chat'
    | '/_layout/'
    | '/_layout/system/agent'
    | '/_layout/system/department'
    | '/_layout/system/queue'
    | '/_layout/system/role'
    | '/_layout/system/user'
    | '/_layout/wiki/documents'
    | '/_layout/wiki/folders'
    | '/_layout/wiki/tiptap-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rag-chat': {
      id: '/_layout/rag-chat'
      path: '/rag-chat'
      fullPath: '/rag-chat'
      preLoaderRoute: typeof LayoutRagChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/model-config': {
      id: '/_layout/model-config'
      path: '/model-config'
      fullPath: '/model-config'
      preLoaderRoute: typeof LayoutModelConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/collection': {
      id: '/_layout/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof LayoutCollectionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app-setting': {
      id: '/_layout/app-setting'
      path: '/app-setting'
      fullPath: '/app-setting'
      preLoaderRoute: typeof LayoutAppSettingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account': {
      id: '/_layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wiki/tiptap-editor': {
      id: '/_layout/wiki/tiptap-editor'
      path: '/wiki/tiptap-editor'
      fullPath: '/wiki/tiptap-editor'
      preLoaderRoute: typeof LayoutWikiTiptapEditorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wiki/folders': {
      id: '/_layout/wiki/folders'
      path: '/wiki/folders'
      fullPath: '/wiki/folders'
      preLoaderRoute: typeof LayoutWikiFoldersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wiki/documents': {
      id: '/_layout/wiki/documents'
      path: '/wiki/documents'
      fullPath: '/wiki/documents'
      preLoaderRoute: typeof LayoutWikiDocumentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/user': {
      id: '/_layout/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof LayoutSystemUserRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/role': {
      id: '/_layout/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof LayoutSystemRoleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/queue': {
      id: '/_layout/system/queue'
      path: '/system/queue'
      fullPath: '/system/queue'
      preLoaderRoute: typeof LayoutSystemQueueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/department': {
      id: '/_layout/system/department'
      path: '/system/department'
      fullPath: '/system/department'
      preLoaderRoute: typeof LayoutSystemDepartmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/agent': {
      id: '/_layout/system/agent'
      path: '/system/agent'
      fullPath: '/system/agent'
      preLoaderRoute: typeof LayoutSystemAgentRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAccountRoute: typeof LayoutAccountRoute
  LayoutAppSettingRoute: typeof LayoutAppSettingRoute
  LayoutCollectionRoute: typeof LayoutCollectionRoute
  LayoutModelConfigRoute: typeof LayoutModelConfigRoute
  LayoutRagChatRoute: typeof LayoutRagChatRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSystemAgentRoute: typeof LayoutSystemAgentRoute
  LayoutSystemDepartmentRoute: typeof LayoutSystemDepartmentRoute
  LayoutSystemQueueRoute: typeof LayoutSystemQueueRoute
  LayoutSystemRoleRoute: typeof LayoutSystemRoleRoute
  LayoutSystemUserRoute: typeof LayoutSystemUserRoute
  LayoutWikiDocumentsRoute: typeof LayoutWikiDocumentsRoute
  LayoutWikiFoldersRoute: typeof LayoutWikiFoldersRoute
  LayoutWikiTiptapEditorRoute: typeof LayoutWikiTiptapEditorRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountRoute: LayoutAccountRoute,
  LayoutAppSettingRoute: LayoutAppSettingRoute,
  LayoutCollectionRoute: LayoutCollectionRoute,
  LayoutModelConfigRoute: LayoutModelConfigRoute,
  LayoutRagChatRoute: LayoutRagChatRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSystemAgentRoute: LayoutSystemAgentRoute,
  LayoutSystemDepartmentRoute: LayoutSystemDepartmentRoute,
  LayoutSystemQueueRoute: LayoutSystemQueueRoute,
  LayoutSystemRoleRoute: LayoutSystemRoleRoute,
  LayoutSystemUserRoute: LayoutSystemUserRoute,
  LayoutWikiDocumentsRoute: LayoutWikiDocumentsRoute,
  LayoutWikiFoldersRoute: LayoutWikiFoldersRoute,
  LayoutWikiTiptapEditorRoute: LayoutWikiTiptapEditorRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
