/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWikiIndexRouteImport } from './routes/_layout/wiki/index'
import { Route as LayoutSystemModelConfigRouteImport } from './routes/_layout/system/model-config'
import { Route as LayoutSystemAgentConfigRouteImport } from './routes/_layout/system/agent-config'
import { Route as LayoutLearnProfileRouteImport } from './routes/_layout/learn/profile'
import { Route as LayoutLearnJournalRouteImport } from './routes/_layout/learn/journal'
import { Route as LayoutLearnFeynmanRouteImport } from './routes/_layout/learn/feynman'
import { Route as LayoutCommonAppSettingRouteImport } from './routes/_layout/common/app-setting'
import { Route as LayoutLearnSessionSessionIdRouteImport } from './routes/_layout/learn/session/$sessionId'
import { Route as LayoutLearnFeynmanPracticeDocumentIdRouteImport } from './routes/_layout/learn/feynman-practice/$documentId'
import { Route as LayoutLearnFeynmanPracticeDocumentIdIndexRouteImport } from './routes/_layout/learn/feynman-practice/$documentId/index'
import { Route as LayoutLearnFeynmanPracticeDocumentIdTeacherRouteImport } from './routes/_layout/learn/feynman-practice/$documentId/teacher'
import { Route as LayoutLearnFeynmanPracticeDocumentIdListenerRouteImport } from './routes/_layout/learn/feynman-practice/$documentId/listener'
import { Route as LayoutLearnFeynmanPracticeDocumentIdCuratorRouteImport } from './routes/_layout/learn/feynman-practice/$documentId/curator'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWikiIndexRoute = LayoutWikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemModelConfigRoute = LayoutSystemModelConfigRouteImport.update({
  id: '/system/model-config',
  path: '/system/model-config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemAgentConfigRoute = LayoutSystemAgentConfigRouteImport.update({
  id: '/system/agent-config',
  path: '/system/agent-config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearnProfileRoute = LayoutLearnProfileRouteImport.update({
  id: '/learn/profile',
  path: '/learn/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearnJournalRoute = LayoutLearnJournalRouteImport.update({
  id: '/learn/journal',
  path: '/learn/journal',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearnFeynmanRoute = LayoutLearnFeynmanRouteImport.update({
  id: '/learn/feynman',
  path: '/learn/feynman',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommonAppSettingRoute = LayoutCommonAppSettingRouteImport.update({
  id: '/common/app-setting',
  path: '/common/app-setting',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearnSessionSessionIdRoute =
  LayoutLearnSessionSessionIdRouteImport.update({
    id: '/learn/session/$sessionId',
    path: '/learn/session/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLearnFeynmanPracticeDocumentIdRoute =
  LayoutLearnFeynmanPracticeDocumentIdRouteImport.update({
    id: '/learn/feynman-practice/$documentId',
    path: '/learn/feynman-practice/$documentId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLearnFeynmanPracticeDocumentIdIndexRoute =
  LayoutLearnFeynmanPracticeDocumentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutLearnFeynmanPracticeDocumentIdRoute,
  } as any)
const LayoutLearnFeynmanPracticeDocumentIdTeacherRoute =
  LayoutLearnFeynmanPracticeDocumentIdTeacherRouteImport.update({
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => LayoutLearnFeynmanPracticeDocumentIdRoute,
  } as any)
const LayoutLearnFeynmanPracticeDocumentIdListenerRoute =
  LayoutLearnFeynmanPracticeDocumentIdListenerRouteImport.update({
    id: '/listener',
    path: '/listener',
    getParentRoute: () => LayoutLearnFeynmanPracticeDocumentIdRoute,
  } as any)
const LayoutLearnFeynmanPracticeDocumentIdCuratorRoute =
  LayoutLearnFeynmanPracticeDocumentIdCuratorRouteImport.update({
    id: '/curator',
    path: '/curator',
    getParentRoute: () => LayoutLearnFeynmanPracticeDocumentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/common/app-setting': typeof LayoutCommonAppSettingRoute
  '/learn/feynman': typeof LayoutLearnFeynmanRoute
  '/learn/journal': typeof LayoutLearnJournalRoute
  '/learn/profile': typeof LayoutLearnProfileRoute
  '/system/agent-config': typeof LayoutSystemAgentConfigRoute
  '/system/model-config': typeof LayoutSystemModelConfigRoute
  '/wiki/': typeof LayoutWikiIndexRoute
  '/learn/feynman-practice/$documentId': typeof LayoutLearnFeynmanPracticeDocumentIdRouteWithChildren
  '/learn/session/$sessionId': typeof LayoutLearnSessionSessionIdRoute
  '/learn/feynman-practice/$documentId/curator': typeof LayoutLearnFeynmanPracticeDocumentIdCuratorRoute
  '/learn/feynman-practice/$documentId/listener': typeof LayoutLearnFeynmanPracticeDocumentIdListenerRoute
  '/learn/feynman-practice/$documentId/teacher': typeof LayoutLearnFeynmanPracticeDocumentIdTeacherRoute
  '/learn/feynman-practice/$documentId/': typeof LayoutLearnFeynmanPracticeDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/common/app-setting': typeof LayoutCommonAppSettingRoute
  '/learn/feynman': typeof LayoutLearnFeynmanRoute
  '/learn/journal': typeof LayoutLearnJournalRoute
  '/learn/profile': typeof LayoutLearnProfileRoute
  '/system/agent-config': typeof LayoutSystemAgentConfigRoute
  '/system/model-config': typeof LayoutSystemModelConfigRoute
  '/wiki': typeof LayoutWikiIndexRoute
  '/learn/session/$sessionId': typeof LayoutLearnSessionSessionIdRoute
  '/learn/feynman-practice/$documentId/curator': typeof LayoutLearnFeynmanPracticeDocumentIdCuratorRoute
  '/learn/feynman-practice/$documentId/listener': typeof LayoutLearnFeynmanPracticeDocumentIdListenerRoute
  '/learn/feynman-practice/$documentId/teacher': typeof LayoutLearnFeynmanPracticeDocumentIdTeacherRoute
  '/learn/feynman-practice/$documentId': typeof LayoutLearnFeynmanPracticeDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/common/app-setting': typeof LayoutCommonAppSettingRoute
  '/_layout/learn/feynman': typeof LayoutLearnFeynmanRoute
  '/_layout/learn/journal': typeof LayoutLearnJournalRoute
  '/_layout/learn/profile': typeof LayoutLearnProfileRoute
  '/_layout/system/agent-config': typeof LayoutSystemAgentConfigRoute
  '/_layout/system/model-config': typeof LayoutSystemModelConfigRoute
  '/_layout/wiki/': typeof LayoutWikiIndexRoute
  '/_layout/learn/feynman-practice/$documentId': typeof LayoutLearnFeynmanPracticeDocumentIdRouteWithChildren
  '/_layout/learn/session/$sessionId': typeof LayoutLearnSessionSessionIdRoute
  '/_layout/learn/feynman-practice/$documentId/curator': typeof LayoutLearnFeynmanPracticeDocumentIdCuratorRoute
  '/_layout/learn/feynman-practice/$documentId/listener': typeof LayoutLearnFeynmanPracticeDocumentIdListenerRoute
  '/_layout/learn/feynman-practice/$documentId/teacher': typeof LayoutLearnFeynmanPracticeDocumentIdTeacherRoute
  '/_layout/learn/feynman-practice/$documentId/': typeof LayoutLearnFeynmanPracticeDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/common/app-setting'
    | '/learn/feynman'
    | '/learn/journal'
    | '/learn/profile'
    | '/system/agent-config'
    | '/system/model-config'
    | '/wiki/'
    | '/learn/feynman-practice/$documentId'
    | '/learn/session/$sessionId'
    | '/learn/feynman-practice/$documentId/curator'
    | '/learn/feynman-practice/$documentId/listener'
    | '/learn/feynman-practice/$documentId/teacher'
    | '/learn/feynman-practice/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/common/app-setting'
    | '/learn/feynman'
    | '/learn/journal'
    | '/learn/profile'
    | '/system/agent-config'
    | '/system/model-config'
    | '/wiki'
    | '/learn/session/$sessionId'
    | '/learn/feynman-practice/$documentId/curator'
    | '/learn/feynman-practice/$documentId/listener'
    | '/learn/feynman-practice/$documentId/teacher'
    | '/learn/feynman-practice/$documentId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/common/app-setting'
    | '/_layout/learn/feynman'
    | '/_layout/learn/journal'
    | '/_layout/learn/profile'
    | '/_layout/system/agent-config'
    | '/_layout/system/model-config'
    | '/_layout/wiki/'
    | '/_layout/learn/feynman-practice/$documentId'
    | '/_layout/learn/session/$sessionId'
    | '/_layout/learn/feynman-practice/$documentId/curator'
    | '/_layout/learn/feynman-practice/$documentId/listener'
    | '/_layout/learn/feynman-practice/$documentId/teacher'
    | '/_layout/learn/feynman-practice/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wiki/': {
      id: '/_layout/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof LayoutWikiIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/model-config': {
      id: '/_layout/system/model-config'
      path: '/system/model-config'
      fullPath: '/system/model-config'
      preLoaderRoute: typeof LayoutSystemModelConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/agent-config': {
      id: '/_layout/system/agent-config'
      path: '/system/agent-config'
      fullPath: '/system/agent-config'
      preLoaderRoute: typeof LayoutSystemAgentConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/profile': {
      id: '/_layout/learn/profile'
      path: '/learn/profile'
      fullPath: '/learn/profile'
      preLoaderRoute: typeof LayoutLearnProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/journal': {
      id: '/_layout/learn/journal'
      path: '/learn/journal'
      fullPath: '/learn/journal'
      preLoaderRoute: typeof LayoutLearnJournalRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/feynman': {
      id: '/_layout/learn/feynman'
      path: '/learn/feynman'
      fullPath: '/learn/feynman'
      preLoaderRoute: typeof LayoutLearnFeynmanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/common/app-setting': {
      id: '/_layout/common/app-setting'
      path: '/common/app-setting'
      fullPath: '/common/app-setting'
      preLoaderRoute: typeof LayoutCommonAppSettingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/session/$sessionId': {
      id: '/_layout/learn/session/$sessionId'
      path: '/learn/session/$sessionId'
      fullPath: '/learn/session/$sessionId'
      preLoaderRoute: typeof LayoutLearnSessionSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/feynman-practice/$documentId': {
      id: '/_layout/learn/feynman-practice/$documentId'
      path: '/learn/feynman-practice/$documentId'
      fullPath: '/learn/feynman-practice/$documentId'
      preLoaderRoute: typeof LayoutLearnFeynmanPracticeDocumentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/feynman-practice/$documentId/': {
      id: '/_layout/learn/feynman-practice/$documentId/'
      path: '/'
      fullPath: '/learn/feynman-practice/$documentId/'
      preLoaderRoute: typeof LayoutLearnFeynmanPracticeDocumentIdIndexRouteImport
      parentRoute: typeof LayoutLearnFeynmanPracticeDocumentIdRoute
    }
    '/_layout/learn/feynman-practice/$documentId/teacher': {
      id: '/_layout/learn/feynman-practice/$documentId/teacher'
      path: '/teacher'
      fullPath: '/learn/feynman-practice/$documentId/teacher'
      preLoaderRoute: typeof LayoutLearnFeynmanPracticeDocumentIdTeacherRouteImport
      parentRoute: typeof LayoutLearnFeynmanPracticeDocumentIdRoute
    }
    '/_layout/learn/feynman-practice/$documentId/listener': {
      id: '/_layout/learn/feynman-practice/$documentId/listener'
      path: '/listener'
      fullPath: '/learn/feynman-practice/$documentId/listener'
      preLoaderRoute: typeof LayoutLearnFeynmanPracticeDocumentIdListenerRouteImport
      parentRoute: typeof LayoutLearnFeynmanPracticeDocumentIdRoute
    }
    '/_layout/learn/feynman-practice/$documentId/curator': {
      id: '/_layout/learn/feynman-practice/$documentId/curator'
      path: '/curator'
      fullPath: '/learn/feynman-practice/$documentId/curator'
      preLoaderRoute: typeof LayoutLearnFeynmanPracticeDocumentIdCuratorRouteImport
      parentRoute: typeof LayoutLearnFeynmanPracticeDocumentIdRoute
    }
  }
}

interface LayoutLearnFeynmanPracticeDocumentIdRouteChildren {
  LayoutLearnFeynmanPracticeDocumentIdCuratorRoute: typeof LayoutLearnFeynmanPracticeDocumentIdCuratorRoute
  LayoutLearnFeynmanPracticeDocumentIdListenerRoute: typeof LayoutLearnFeynmanPracticeDocumentIdListenerRoute
  LayoutLearnFeynmanPracticeDocumentIdTeacherRoute: typeof LayoutLearnFeynmanPracticeDocumentIdTeacherRoute
  LayoutLearnFeynmanPracticeDocumentIdIndexRoute: typeof LayoutLearnFeynmanPracticeDocumentIdIndexRoute
}

const LayoutLearnFeynmanPracticeDocumentIdRouteChildren: LayoutLearnFeynmanPracticeDocumentIdRouteChildren =
  {
    LayoutLearnFeynmanPracticeDocumentIdCuratorRoute:
      LayoutLearnFeynmanPracticeDocumentIdCuratorRoute,
    LayoutLearnFeynmanPracticeDocumentIdListenerRoute:
      LayoutLearnFeynmanPracticeDocumentIdListenerRoute,
    LayoutLearnFeynmanPracticeDocumentIdTeacherRoute:
      LayoutLearnFeynmanPracticeDocumentIdTeacherRoute,
    LayoutLearnFeynmanPracticeDocumentIdIndexRoute:
      LayoutLearnFeynmanPracticeDocumentIdIndexRoute,
  }

const LayoutLearnFeynmanPracticeDocumentIdRouteWithChildren =
  LayoutLearnFeynmanPracticeDocumentIdRoute._addFileChildren(
    LayoutLearnFeynmanPracticeDocumentIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCommonAppSettingRoute: typeof LayoutCommonAppSettingRoute
  LayoutLearnFeynmanRoute: typeof LayoutLearnFeynmanRoute
  LayoutLearnJournalRoute: typeof LayoutLearnJournalRoute
  LayoutLearnProfileRoute: typeof LayoutLearnProfileRoute
  LayoutSystemAgentConfigRoute: typeof LayoutSystemAgentConfigRoute
  LayoutSystemModelConfigRoute: typeof LayoutSystemModelConfigRoute
  LayoutWikiIndexRoute: typeof LayoutWikiIndexRoute
  LayoutLearnFeynmanPracticeDocumentIdRoute: typeof LayoutLearnFeynmanPracticeDocumentIdRouteWithChildren
  LayoutLearnSessionSessionIdRoute: typeof LayoutLearnSessionSessionIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCommonAppSettingRoute: LayoutCommonAppSettingRoute,
  LayoutLearnFeynmanRoute: LayoutLearnFeynmanRoute,
  LayoutLearnJournalRoute: LayoutLearnJournalRoute,
  LayoutLearnProfileRoute: LayoutLearnProfileRoute,
  LayoutSystemAgentConfigRoute: LayoutSystemAgentConfigRoute,
  LayoutSystemModelConfigRoute: LayoutSystemModelConfigRoute,
  LayoutWikiIndexRoute: LayoutWikiIndexRoute,
  LayoutLearnFeynmanPracticeDocumentIdRoute:
    LayoutLearnFeynmanPracticeDocumentIdRouteWithChildren,
  LayoutLearnSessionSessionIdRoute: LayoutLearnSessionSessionIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
