/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWikiTiptapEditorRouteImport } from './routes/_layout/wiki/tiptap-editor'
import { Route as LayoutSystemUserRouteImport } from './routes/_layout/system/user'
import { Route as LayoutSystemModelConfigRouteImport } from './routes/_layout/system/model-config'
import { Route as LayoutLearnJournalRouteImport } from './routes/_layout/learn/journal'
import { Route as LayoutCommonAppSettingRouteImport } from './routes/_layout/common/app-setting'
import { Route as LayoutCommonAccountRouteImport } from './routes/_layout/common/account'
import { Route as LayoutLearnSessionSessionIdRouteImport } from './routes/_layout/learn/session/$sessionId'
import { Route as LayoutLearnGoalGoalIdRouteImport } from './routes/_layout/learn/goal/$goalId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWikiTiptapEditorRoute = LayoutWikiTiptapEditorRouteImport.update({
  id: '/wiki/tiptap-editor',
  path: '/wiki/tiptap-editor',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemUserRoute = LayoutSystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemModelConfigRoute = LayoutSystemModelConfigRouteImport.update({
  id: '/system/model-config',
  path: '/system/model-config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearnJournalRoute = LayoutLearnJournalRouteImport.update({
  id: '/learn/journal',
  path: '/learn/journal',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommonAppSettingRoute = LayoutCommonAppSettingRouteImport.update({
  id: '/common/app-setting',
  path: '/common/app-setting',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommonAccountRoute = LayoutCommonAccountRouteImport.update({
  id: '/common/account',
  path: '/common/account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearnSessionSessionIdRoute =
  LayoutLearnSessionSessionIdRouteImport.update({
    id: '/learn/session/$sessionId',
    path: '/learn/session/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLearnGoalGoalIdRoute = LayoutLearnGoalGoalIdRouteImport.update({
  id: '/learn/goal/$goalId',
  path: '/learn/goal/$goalId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/common/account': typeof LayoutCommonAccountRoute
  '/common/app-setting': typeof LayoutCommonAppSettingRoute
  '/learn/journal': typeof LayoutLearnJournalRoute
  '/system/model-config': typeof LayoutSystemModelConfigRoute
  '/system/user': typeof LayoutSystemUserRoute
  '/wiki/tiptap-editor': typeof LayoutWikiTiptapEditorRoute
  '/learn/goal/$goalId': typeof LayoutLearnGoalGoalIdRoute
  '/learn/session/$sessionId': typeof LayoutLearnSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/common/account': typeof LayoutCommonAccountRoute
  '/common/app-setting': typeof LayoutCommonAppSettingRoute
  '/learn/journal': typeof LayoutLearnJournalRoute
  '/system/model-config': typeof LayoutSystemModelConfigRoute
  '/system/user': typeof LayoutSystemUserRoute
  '/wiki/tiptap-editor': typeof LayoutWikiTiptapEditorRoute
  '/learn/goal/$goalId': typeof LayoutLearnGoalGoalIdRoute
  '/learn/session/$sessionId': typeof LayoutLearnSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/common/account': typeof LayoutCommonAccountRoute
  '/_layout/common/app-setting': typeof LayoutCommonAppSettingRoute
  '/_layout/learn/journal': typeof LayoutLearnJournalRoute
  '/_layout/system/model-config': typeof LayoutSystemModelConfigRoute
  '/_layout/system/user': typeof LayoutSystemUserRoute
  '/_layout/wiki/tiptap-editor': typeof LayoutWikiTiptapEditorRoute
  '/_layout/learn/goal/$goalId': typeof LayoutLearnGoalGoalIdRoute
  '/_layout/learn/session/$sessionId': typeof LayoutLearnSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/common/account'
    | '/common/app-setting'
    | '/learn/journal'
    | '/system/model-config'
    | '/system/user'
    | '/wiki/tiptap-editor'
    | '/learn/goal/$goalId'
    | '/learn/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/common/account'
    | '/common/app-setting'
    | '/learn/journal'
    | '/system/model-config'
    | '/system/user'
    | '/wiki/tiptap-editor'
    | '/learn/goal/$goalId'
    | '/learn/session/$sessionId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/'
    | '/_layout/common/account'
    | '/_layout/common/app-setting'
    | '/_layout/learn/journal'
    | '/_layout/system/model-config'
    | '/_layout/system/user'
    | '/_layout/wiki/tiptap-editor'
    | '/_layout/learn/goal/$goalId'
    | '/_layout/learn/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wiki/tiptap-editor': {
      id: '/_layout/wiki/tiptap-editor'
      path: '/wiki/tiptap-editor'
      fullPath: '/wiki/tiptap-editor'
      preLoaderRoute: typeof LayoutWikiTiptapEditorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/user': {
      id: '/_layout/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof LayoutSystemUserRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/model-config': {
      id: '/_layout/system/model-config'
      path: '/system/model-config'
      fullPath: '/system/model-config'
      preLoaderRoute: typeof LayoutSystemModelConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/journal': {
      id: '/_layout/learn/journal'
      path: '/learn/journal'
      fullPath: '/learn/journal'
      preLoaderRoute: typeof LayoutLearnJournalRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/common/app-setting': {
      id: '/_layout/common/app-setting'
      path: '/common/app-setting'
      fullPath: '/common/app-setting'
      preLoaderRoute: typeof LayoutCommonAppSettingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/common/account': {
      id: '/_layout/common/account'
      path: '/common/account'
      fullPath: '/common/account'
      preLoaderRoute: typeof LayoutCommonAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/session/$sessionId': {
      id: '/_layout/learn/session/$sessionId'
      path: '/learn/session/$sessionId'
      fullPath: '/learn/session/$sessionId'
      preLoaderRoute: typeof LayoutLearnSessionSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/goal/$goalId': {
      id: '/_layout/learn/goal/$goalId'
      path: '/learn/goal/$goalId'
      fullPath: '/learn/goal/$goalId'
      preLoaderRoute: typeof LayoutLearnGoalGoalIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCommonAccountRoute: typeof LayoutCommonAccountRoute
  LayoutCommonAppSettingRoute: typeof LayoutCommonAppSettingRoute
  LayoutLearnJournalRoute: typeof LayoutLearnJournalRoute
  LayoutSystemModelConfigRoute: typeof LayoutSystemModelConfigRoute
  LayoutSystemUserRoute: typeof LayoutSystemUserRoute
  LayoutWikiTiptapEditorRoute: typeof LayoutWikiTiptapEditorRoute
  LayoutLearnGoalGoalIdRoute: typeof LayoutLearnGoalGoalIdRoute
  LayoutLearnSessionSessionIdRoute: typeof LayoutLearnSessionSessionIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCommonAccountRoute: LayoutCommonAccountRoute,
  LayoutCommonAppSettingRoute: LayoutCommonAppSettingRoute,
  LayoutLearnJournalRoute: LayoutLearnJournalRoute,
  LayoutSystemModelConfigRoute: LayoutSystemModelConfigRoute,
  LayoutSystemUserRoute: LayoutSystemUserRoute,
  LayoutWikiTiptapEditorRoute: LayoutWikiTiptapEditorRoute,
  LayoutLearnGoalGoalIdRoute: LayoutLearnGoalGoalIdRoute,
  LayoutLearnSessionSessionIdRoute: LayoutLearnSessionSessionIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
